Brendon/bootcamp page
codinglabsau/bootcamp4 pull request #13
Opened 2020-04-02 10:32 UTC by brendon250891

## Bootcamp Landing Page
- Made a landing page for users to view information about courses being offered through bootcamp.
- Based of a mockup i saw a while ago in the docs and files on basecamp.
- Created a course factory to mock some data.
- Used the pipe symbol to act as delimiter to create the list for the course contents so it can be stored as a string in the database.
- Created a course controller for route handling.

![image](https://user-images.githubusercontent.com/23717298/78238853-c1df4d00-7528-11ea-818e-d423bd885aba.png)

![image](https://user-images.githubusercontent.com/23717298/78238992-ea674700-7528-11ea-9a6d-2f7ba8771778.png)

2020-04-09 04:11 UTC, brendon250891 commented
# Couse Change
- Added description column to $casts as an array.
- This removed the need to complicate the seeding and retrieving of the description to/from the database.

2020-04-14 06:00 UTC, stevethomas requested changes

2020-04-14 06:00 UTC, stevethomas commented on app/Http/Controllers/CourseController.php
> +        return view('bootcamp.index', compact('courses'));
any reason why this isn't `courses.index`?

2020-04-14 06:00 UTC, stevethomas commented on database/seeds/DatabaseSeeder.php
> +//        }
hmm this will probably create a conflict with master once the other branch is merged. Not a lot you can do, will have to resolve conflicts by hand.

2020-04-14 06:00 UTC, stevethomas commented on public/js/app.js
> +module.exports = __webpack_require__(/*! /Users/brendon/code/bootcamp4/resources/css/app.css */"./resources/css/app.css");
this file should be .gitignored one of the branches or this will keep happening.

2020-04-14 06:00 UTC, stevethomas commented on routes/web.php
> +   'index' => 'bootcamp',
same again, I would have just called this `courses` as it is the index for courses.

2020-04-14 06:54 UTC, brendon250891 commented
##Changes Made
- Renamed the route bootcamp to courses
- Moved the courses index.blade.php to the courses directory
- Added a path function to the Course class
- Added public/css/* and public/js* to my gitignore.

2020-04-14 22:46 UTC, stevethomas approved these changes

2020-04-14 23:02 UTC, merged